const vm=require('vm'),fs=require('fs'),assert=require('node:assert/strict');
const window={};vm.runInNewContext(fs.readFileSync('source/dashboard/static/message-unread.js','utf8'),{window,document:{readyState:'loading',addEventListener(){}}});
const {mark,unread}=window.RFMessageRead;
let seen={};assert.equal(unread({'0':10,'1':20},seen),true);
seen=mark(seen,'0',10);assert.equal(unread({'0':10,'1':20},seen),true);
seen=mark(seen,'1',20);assert.equal(unread({'0':10,'1':20},seen),false);
seen=mark(seen,'0',5);assert.equal(seen['0'],10);
assert.equal(unread({'0':11,'1':20},seen),true);
assert.equal(mark(seen,'__proto__',100),seen);assert.equal(mark(seen,'0',NaN),seen);
assert.equal(unread({},seen),false);
console.log('PASS: read marks are per channel, monotonic, reject invalid IDs, and detect later messages');
