(() => {
 'use strict';
 const $=id=>document.getElementById(id),nodeNames=['Basecamp','Ridge Relay','Garden Gate','Trail Pack','Library Roof','North Window','Workshop','Creek Walk','Hilltop','Market Square','Mobile One','South Porch','Orchard','Water Tower','Field Kit','Park Bench'];
 let center=[39.7392,-104.9903],place='Denver',nodes=[],chart,map,markers,grid,selected,searchGeneration=0;
 const number=n=>Math.round(n).toLocaleString();
 function random(seed){return()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};}
 function element(tag,text,cls){const el=document.createElement(tag);if(text!=null)el.textContent=text;if(cls)el.className=cls;return el;}
 function generate(){
  const rand=random(Math.abs(Math.round(center[0]*1000)+Math.round(center[1]*10000)));
  nodes=nodeNames.map((name,i)=>{const angle=rand()*Math.PI*2,distance=i===0?0:1+rand()*21,lat=center[0]+Math.cos(angle)*distance/111.32,lon=center[1]+Math.sin(angle)*distance/(111.32*Math.cos(center[0]*Math.PI/180));
   return {name,id:'!'+(0xf0000000+i).toString(16),lat,lon,distance,role:i===1||i===13?'ROUTER_LATE':'CLIENT',hardware:['Portable radio','Solar relay','Base receiver'][i%3],snr:Math.round((12-distance*1.1+(rand()-.5)*8)*4)/4,rssi:Math.round(-65-distance*2+rand()*8),battery:i===0?101:Math.round(30+rand()*70),hops:distance<6?0:1+Math.floor(rand()*4),rate:2+rand()*10,age:Math.round(rand()*180),mobile:[3,7,10,14].includes(i)};});
  render();renderMessages();if(map)renderMap();
 }
 function hours(){return Number($('window').value);}
 function packets(){return nodes.reduce((sum,n)=>sum+Math.round(n.rate*hours()),0);}
 function render(){
  $('place').textContent=place+' · sample network';const total=packets(),direct=Math.round(nodes.filter(n=>n.hops===0).reduce((s,n)=>s+n.rate*hours(),0)/total*100);
  $('stats').replaceChildren(...[['Fictional nodes',nodes.length],['Sample packets',number(total)],['Direct observations',direct+'%'],['Sample channel load','3.8%']].map(([label,value])=>{const box=element('div',null,'stat');box.append(element('span',label),element('strong',value));return box;}));
  const buckets=12,values=Array.from({length:buckets},(_,i)=>Math.round(total/buckets*(.65+.65*Math.sin((i+1)*.8)**2))),sum=values.reduce((a,b)=>a+b,0);values[values.length-1]+=total-sum;
  const labels=values.map((_,i)=>new Date(Date.now()-(buckets-1-i)*hours()*3600000/buckets).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));
  if(chart)chart.destroy();chart=new Chart($('traffic'),{type:'bar',data:{labels,datasets:[{label:'Simulated packets',data:values,backgroundColor:'#79ecaa',borderRadius:4}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#aebdb2',maxTicksLimit:6},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#aebdb2'},grid:{color:'#33483a'}}}}});
  $('trafficSummary').textContent=`${number(total)} fictional packets across ${hours()} hours. Peak sample bucket: ${Math.max(...values)} packets.`;
  $('observations').replaceChildren(...[`${direct}% of sample packets arrive directly. Relayed signal values describe the last link, not the whole route.`,`${nodes.filter(n=>n.mobile).length} fictional mobile nodes move through this scenario.`,`${nodes.filter(n=>n.snr<0).length} nodes have a negative SNR in this sample—still plausible for LoRa reception.`].map(t=>element('p',t)));
  $('recent').replaceChildren(...[...nodes].sort((a,b)=>a.age-b.age).slice(0,5).map(nodeRow));renderNodes();renderScenario();
  $('lnaNote').textContent='In a fictional matched-sender comparison, the OFF period heard 112 packets and the ON period heard 126. Median SNR changed from −3.0 dB to −2.5 dB. The sample is too small to claim a reliable improvement.';
 }
 function nodeRow(n){const row=element('div',null,'node-row'),left=element('div'),button=element('button',(n.mobile?'↗ ':'')+n.name);button.onclick=()=>openNode(n);left.append(button,element('small',`${n.role} · ${n.hardware} · ${n.age} min ago`));const right=element('div');right.append(element('span',`${n.snr} dB SNR`,'badge'),element('small',n.hops?`${n.hops} hops`:'Direct'));row.append(left,right);return row;}
 function renderNodes(){const q=$('nodeSearch').value.toLowerCase();const filtered=nodes.filter(n=>(n.name+' '+n.role+' '+n.hardware).toLowerCase().includes(q));$('nodeList').replaceChildren(...filtered.map(nodeRow));if(!filtered.length)$('nodeList').append(element('p','No matching fictional nodes.'));}
 function openNode(n){selected=n;$('nodeTitle').textContent=n.name;const dl=element('dl');for(const [label,value] of [['Sample ID',n.id],['Role',n.role],['Signal',`${n.rssi} dBm / ${n.snr} dB SNR`],['Route',n.hops?`${n.hops} hops`:'Direct'],['Power',n.battery===101?'External power':n.battery+'%'],['Sample activity',number(n.rate*hours())+' packets'],['Distance to center',n.distance.toFixed(1)+' km'],['Position',`${n.lat.toFixed(4)}, ${n.lon.toFixed(4)}`]]){const cell=element('div');cell.append(element('dt',label),element('dd',value));dl.append(cell);}$('nodeDetails').replaceChildren(dl);$('traceResult').textContent='';$('trace').disabled=n===nodes[0];$('nodeDialog').showModal();}
 function renderScenario(){const cancel=Number($('cancel').value),candidates=Math.round(packets()*.28),extra=Math.round(candidates*(1-cancel/100));$('cancelValue').textContent=cancel+'%';$('scenario').textContent=`With this assumption: about ${number(extra)} additional rebroadcasts, or ${(extra*.4/60).toFixed(1)} extra transmit minutes over ${hours()} hours.`;}
 function renderMap(){
  if(!map){map=L.map('demoMap').setView(center,11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);markers=L.layerGroup().addTo(map);grid=L.layerGroup();}
  markers.clearLayers();grid.clearLayers();
  for(const n of nodes){L.circleMarker([n.lat,n.lon],{radius:n.mobile?8:7,color:n.age>120?'#b27a23':'#217746',weight:2,fillColor:n.age>120?'#f3c365':'#79ecaa',fillOpacity:.9}).bindTooltip(n.name+' · fictional node').on('click',()=>openNode(n)).addTo(markers);}
  const step=6.437/111.32,lonStep=step/Math.cos(center[0]*Math.PI/180);const rand=random(84);
  for(let y=-3;y<3;y++)for(let x=-3;x<3;x++){const south=center[0]+y*step,west=center[1]+x*lonStep;L.rectangle([[south,west],[south+step,west+lonStep]],{interactive:false,color:'#52715c',weight:1,fillColor:rand()>.3?'#56b777':'#e8b759',fillOpacity:.08+rand()*.24}).addTo(grid);}
  if($('coverage').checked)grid.addTo(map);else map.removeLayer(grid);map.fitBounds(L.latLngBounds(nodes.map(n=>[n.lat,n.lon])).pad(.12));
 }
 function setCenter(lat,lon,name){if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>75||Math.abs(lon)>179){throw Error('Choose latitude between −75 and 75 and longitude between −179 and 179.');}center=[lat,lon];place=name;generate();$('locationStatus').textContent='Sample network generated. All nodes and activity remain fictional.';}
 $('locationForm').onsubmit=async event=>{event.preventDefault();const query=$('location').value.trim(),generation=++searchGeneration;const coords=query.match(/^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$/);$('locate').disabled=true;try{if(coords){setCenter(Number(coords[1]),Number(coords[2]),'Chosen coordinates');return;}if(query.length<2||query.length>150)throw Error('Enter a city or latitude, longitude.');$('locationStatus').textContent='Looking up the city…';const response=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(query),{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('City lookup unavailable. Try coordinates or a sample location.');const result=await response.json();if(generation!==searchGeneration)return;if(!result.length)throw Error('Location not found. Try a city and country, or coordinates.');setCenter(Number(result[0].lat),Number(result[0].lon),query);}catch(error){$('locationStatus').textContent=error.message;}finally{$('locate').disabled=false;}};
 document.querySelectorAll('[data-center]').forEach(button=>button.onclick=()=>{searchGeneration++;const [lat,lon]=button.dataset.center.split(',').map(Number);$('location').value=button.dataset.name;setCenter(lat,lon,button.dataset.name);});
 document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.panel').forEach(panel=>panel.hidden=panel.id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(button.dataset.tab==='map'){if(!map)renderMap();requestAnimationFrame(()=>map.invalidateSize());}if(button.dataset.tab==='overview')chart.resize();});
 $('window').onchange=render;$('nodeSearch').oninput=renderNodes;$('cancel').oninput=renderScenario;$('coverage').onchange=()=>{if(map){if($('coverage').checked)grid.addTo(map);else map.removeLayer(grid);}};
 $('closeDialog').onclick=()=>$('nodeDialog').close();$('trace').onclick=()=>{$('traceResult').textContent='Simulated route: Basecamp → '+(selected.hops?'Ridge Relay → ':'')+selected.name+'. Example only; no radio request was sent.';};
 function renderMessages(){$('messageList').replaceChildren();for(const [name,text] of [['Trail Pack','At the trail junction. Checking in.'],['Basecamp','Received. Signal looks steady in this sample.'],['Garden Gate','Solar battery holding at 82%.']]){const entry=element('article',null,'message');entry.append(element('strong',name),element('p',text));$('messageList').append(entry);}}
 $('messageForm').onsubmit=event=>{event.preventDefault();const value=$('message').value.trim();if(!value)return;const entry=element('article',null,'message');entry.append(element('strong','You · demo only'),element('p',value));$('messageList').append(entry);$('message').value='';$('sendStatus').textContent='Added locally to this demo. No radio transmission.';};
 generate();
})();
